trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'devops_registry'
    repository: 'Azure Container Registry'
    command: 'build'
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker image build'

- task: Docker@2
  inputs:
    containerRegistry: 'devops_registry'
    repository: 'Azure Container Registry'
    command: 'push'
  displayName: 'Docker image push'
